apiVersion: apps/v1
kind: Deployment
metadata:
  name: suresh-construction-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: suresh-construction
  template:
    metadata:
      labels:
        app: suresh-construction
    spec:
      containers:
      - name: suresh-construction
        image: maheshsoft/constraction-app:1.0.0   # replace with your DockerHub username
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: suresh-construction-service
spec:
  selector:
    app: suresh-construction
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31122   # ðŸ‘ˆ correctly placed here
  type: NodePort
